Repository dnd-side-project/dnd-11th-6-backend, pull requests merged in 2024-08, with the labels that each got.

#28 [주최자] 모임 생성 API
  build.gradle
  src/docs/asciidoc/meeting/create-meeting.adoc
  src/docs/asciidoc/meeting/meeting.adoc
  src/main/java/com/dnd/snappy/SnappyApplication.java
  src/main/java/com/dnd/snappy/common/error/CommonErrorCode.java
  src/main/java/com/dnd/snappy/common/error/GlobalExceptionHandler.java
  src/main/java/com/dnd/snappy/common/error/exception/DuplicationException.java
  src/main/java/com/dnd/snappy/controller/v1/meeting/MeetingController.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingEntityDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingRequestDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/response/CreateMeetingResponseDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/com/dnd/snappy/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/snappy/domain/meeting/entity/MeetingLinkStatus.java
  src/main/java/com/dnd/snappy/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/snappy/domain/meeting/service/MeetingService.java
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
  src/test/java/com/dnd/snappy/domain/meeting/service/MeetingServiceTest.java
  src/test/java/com/dnd/snappy/support/RestDocsSupport.java
Labels: Feature

#31 [주최자] S3 이미지 업로드 기능 설정 및 모임 생성 시 대표 사진 업로드
  build.gradle
  src/docs/asciidoc/meeting/create-meeting.adoc
  src/main/java/com/dnd/snappy/common/config/S3Config.java
  src/main/java/com/dnd/snappy/common/error/GlobalExceptionHandler.java
  src/main/java/com/dnd/snappy/common/error/exception/ImageException.java
  src/main/java/com/dnd/snappy/controller/v1/meeting/MeetingController.java
  src/main/java/com/dnd/snappy/controller/v1/snap/SnapController.java
  src/main/java/com/dnd/snappy/controller/v1/snap/request/.gitkeep
  src/main/java/com/dnd/snappy/controller/v1/snap/response/.gitkeep
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingEntityDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingRequestDto.java
  src/main/java/com/dnd/snappy/domain/meeting/exception/MeetingErrorCode.java
  src/main/java/com/dnd/snappy/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/snappy/domain/photo/repository/PhotoRepository.java
  src/main/java/com/dnd/snappy/domain/photo/service/PhotoService.java
  src/main/java/com/dnd/snappy/domain/snap/dto/request/.gitkeep
  src/main/java/com/dnd/snappy/domain/snap/dto/response/.gitkeep
  src/main/java/com/dnd/snappy/domain/snap/entity/Snap.java
  src/main/java/com/dnd/snappy/domain/snap/exception/.gitkeep
  src/main/java/com/dnd/snappy/domain/snap/repository/SnapRepository.java
  src/main/java/com/dnd/snappy/domain/snap/service/SnapService.java
  src/main/java/com/dnd/snappy/infrastructure/exception/ImageErrorCode.java
  src/main/java/com/dnd/snappy/infrastructure/uploader/ImageUploader.java
  src/main/java/com/dnd/snappy/infrastructure/uploader/S3ImageUploader.java
  src/main/resources/application.yml
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
  src/test/java/com/dnd/snappy/domain/meeting/service/MeetingServiceTest.java
Labels: Feature

#34 [주최자] 모임 링크 공유하기
  src/docs/asciidoc/meeting/create-meeting.adoc
  src/docs/asciidoc/meeting/meeting.adoc
  src/docs/asciidoc/meeting/shareable-meeting-link.adoc
  src/main/java/com/dnd/snappy/controller/v1/meeting/MeetingController.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/response/ShareMeetingLinkResponseDto.java
  src/main/java/com/dnd/snappy/domain/meeting/service/MeetingService.java
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
  src/test/java/com/dnd/snappy/domain/meeting/service/MeetingServiceTest.java
Labels: Feature

#38 예외 반환 로직 수정
  src/main/java/com/dnd/snappy/common/dto/ErrorResponseDto.java
  src/main/java/com/dnd/snappy/common/dto/ResponseDto.java
  src/main/java/com/dnd/snappy/controller/v1/participant/ParticipantController.java
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
  src/test/java/com/dnd/snappy/controller/v1/participant/ParticipantControllerTest.java
Labels: fix

#41 Refactor/#40
  src/docs/asciidoc/meeting/create-meeting.adoc
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingEntityDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingRequestDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/response/CreateMeetingResponseDto.java
  src/main/java/com/dnd/snappy/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/snappy/domain/meeting/exception/MeetingErrorCode.java
  src/main/java/com/dnd/snappy/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/dnd/snappy/domain/meeting/service/MeetingService.java
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/meeting/create-meeting.html
  src/main/resources/static/docs/meeting/find-by-meeting-link.html
  src/main/resources/static/docs/meeting/meeting.html
  src/main/resources/static/docs/meeting/shareable-meeting-link.html
  src/main/resources/static/docs/meeting/validate-meeting-password-leader.html
  src/main/resources/static/docs/meeting/validate-meeting-password.html
  src/main/resources/static/docs/participant/join-meeting.html
  src/main/resources/static/docs/participant/participant.html
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
  src/test/java/com/dnd/snappy/domain/meeting/service/MeetingServiceTest.java
Labels: refactor

#42 [인증] jwt를 이용한 인증, 인가 구현
  src/docs/asciidoc/auth/auth.adoc
  src/docs/asciidoc/auth/refresh-token.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/snappy/common/error/CommonErrorCode.java
  src/main/java/com/dnd/snappy/common/error/GlobalExceptionHandler.java
  src/main/java/com/dnd/snappy/common/error/exception/BusinessException.java
  src/main/java/com/dnd/snappy/controller/v1/auth/AuthController.java
  src/main/java/com/dnd/snappy/controller/v1/auth/CookieManager.java
  src/main/java/com/dnd/snappy/controller/v1/auth/JwtTokenExtractor.java
  src/main/java/com/dnd/snappy/controller/v1/auth/interceptor/MeetingParticipationInterceptor.java
  src/main/java/com/dnd/snappy/controller/v1/auth/interceptor/config/InterceptorConfig.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/AuthInfo.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/AuthInfoArgumentResolver.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/AuthPrincipal.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/RefreshAuthInfo.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/RefreshAuthPrincipal.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/TokenRefreshArgumentResolver.java
  src/main/java/com/dnd/snappy/controller/v1/auth/resolver/config/ResolverConfig.java
  src/main/java/com/dnd/snappy/controller/v1/participant/ParticipantController.java
  src/main/java/com/dnd/snappy/domain/auth/dto/response/ReissueTokenResponseDto.java
  src/main/java/com/dnd/snappy/domain/auth/dto/response/TokenInfo.java
  src/main/java/com/dnd/snappy/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/dnd/snappy/domain/auth/service/AuthCookieManager.java
  src/main/java/com/dnd/snappy/domain/auth/service/AuthService.java
  src/main/java/com/dnd/snappy/domain/auth/service/AuthTokenCookieNameGenerator.java
  src/main/java/com/dnd/snappy/domain/auth/service/JwtTokenExtractor.java
  src/main/java/com/dnd/snappy/domain/auth/service/JwtTokenStrategy.java
  src/main/java/com/dnd/snappy/domain/auth/service/PathVariableExtractor.java
  src/main/java/com/dnd/snappy/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/snappy/domain/meeting/exception/.gitkeep
  src/main/java/com/dnd/snappy/domain/meeting/service/MeetingService.java
  src/main/java/com/dnd/snappy/domain/participant/dto/response/CreateParticipantResponseDto.java
  src/main/java/com/dnd/snappy/domain/participant/dto/response/ParticipationResponseDto.java
  src/main/java/com/dnd/snappy/domain/participant/exception/ParticipantErrorCode.java
  src/main/java/com/dnd/snappy/domain/participant/repository/ParticipantRepository.java
  src/main/java/com/dnd/snappy/domain/participant/service/ParticipantService.java
  src/main/java/com/dnd/snappy/domain/participant/service/ParticipationService.java
  src/main/java/com/dnd/snappy/domain/token/entity/RefreshToken.java
  src/main/java/com/dnd/snappy/domain/token/exception/TokenErrorCode.java
  src/main/java/com/dnd/snappy/domain/token/service/TokenProvider.java
  src/main/java/com/dnd/snappy/domain/token/service/TokenService.java
  src/main/java/com/dnd/snappy/domain/token/service/TokenType.java
  src/test/java/com/dnd/snappy/controller/v1/auth/AuthControllerTest.java
  src/test/java/com/dnd/snappy/controller/v1/auth/interceptor/MeetingParticipationInterceptorTest.java
  src/test/java/com/dnd/snappy/controller/v1/auth/resolver/AuthInfoArgumentResolverTest.java
  src/test/java/com/dnd/snappy/controller/v1/participant/ParticipantControllerTest.java
  src/test/java/com/dnd/snappy/domain/auth/service/AuthCookieManagerTest.java
  src/test/java/com/dnd/snappy/domain/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/snappy/domain/auth/service/AuthTokenCookieNameGeneratorTest.java
  src/test/java/com/dnd/snappy/domain/auth/service/JwtTokenExtractorTest.java
  src/test/java/com/dnd/snappy/domain/auth/service/JwtTokenStrategyTest.java
  src/test/java/com/dnd/snappy/domain/auth/service/PathVariableExtractorTest.java
  src/test/java/com/dnd/snappy/domain/participant/service/ParticipantServiceTest.java
  src/test/java/com/dnd/snappy/domain/participant/service/ParticipationServiceTest.java
  src/test/java/com/dnd/snappy/domain/token/service/TokenProviderTest.java
  src/test/java/com/dnd/snappy/domain/token/service/TokenServiceTest.java
  src/test/java/com/dnd/snappy/support/IntegrationTestSupport.java
Labels: Feature

#53 [참가자] 닉네임 중복 여부 확인 api개발
  src/docs/asciidoc/participant/check-nickname.adoc
  src/docs/asciidoc/participant/participant.adoc
  src/main/java/com/dnd/snappy/controller/v1/auth/interceptor/config/InterceptorConfig.java
  src/main/java/com/dnd/snappy/controller/v1/participant/ParticipantController.java
  src/main/java/com/dnd/snappy/controller/v1/participant/response/CheckDuplicateNicknameResponse.java
  src/main/java/com/dnd/snappy/domain/participant/service/ParticipantService.java
  src/test/java/com/dnd/snappy/controller/v1/participant/ParticipantControllerTest.java
Labels: Feature

#50 [주최자] 모임 미션 생성/수정/삭제
  src/docs/asciidoc/meeting/create-meeting.adoc
  src/docs/asciidoc/mission/create-mission.adoc
  src/docs/asciidoc/mission/delete-mission.adoc
  src/docs/asciidoc/mission/mission.adoc
  src/docs/asciidoc/mission/modify-mission.adoc
  src/main/java/com/dnd/snappy/common/dto/ResponseDto.java
  src/main/java/com/dnd/snappy/controller/v1/mission/MissionController.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/CreateMeetingRequestDto.java
  src/main/java/com/dnd/snappy/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/snappy/domain/mission/dto/request/.gitkeep
  src/main/java/com/dnd/snappy/domain/mission/dto/request/CreateMissionEntityDto.java
  src/main/java/com/dnd/snappy/domain/mission/dto/request/CreateMissionRequestDto.java
  src/main/java/com/dnd/snappy/domain/mission/dto/request/ModifyMissionRequestDto.java
  src/main/java/com/dnd/snappy/domain/mission/dto/response/CreateMissionResponseDto.java
  src/main/java/com/dnd/snappy/domain/mission/dto/response/ModifyMissionResponseDto.java
  src/main/java/com/dnd/snappy/domain/mission/entity/Mission.java
  src/main/java/com/dnd/snappy/domain/mission/exception/.gitkeep
  src/main/java/com/dnd/snappy/domain/mission/exception/MissionErrorCode.java
  src/main/java/com/dnd/snappy/domain/mission/repository/MissionParticipantRepository.java
  src/main/java/com/dnd/snappy/domain/mission/service/MissionService.java
  src/main/java/com/dnd/snappy/domain/mission/service/MissionValidationService.java
  src/main/java/com/dnd/snappy/domain/participant/entity/Participant.java
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
  src/test/java/com/dnd/snappy/controller/v1/mission/MissionControllerTest.java
  src/test/java/com/dnd/snappy/domain/mission/service/MissionServiceTest.java
Labels: Feature, fix

#56 Feature/#46
  src/docs/asciidoc/snap/find-meeting-mission-snap-in-meeting.adoc
  src/docs/asciidoc/snap/find-random-mission-snap-in-meeting.adoc
  src/docs/asciidoc/snap/find-snaps-in-meeting.adoc
  src/docs/asciidoc/snap/snap.adoc
  src/main/java/com/dnd/snappy/controller/v1/snap/SnapController.java
  src/main/java/com/dnd/snappy/domain/snap/service/MeetingMissionSnapService.java
  src/main/java/com/dnd/snappy/domain/snap/service/RandomMissionSnapService.java
  src/test/java/com/dnd/snappy/controller/v1/snap/SnapControllerTest.java
Labels: Feature

#57 feat: 모임내 내가 찍은 사진 커서 기반 페이지네이션 조회 api 구현 (#46)
  src/docs/asciidoc/snap/find-participant-snaps-in-meeting.adoc
  src/docs/asciidoc/snap/snap.adoc
  src/main/java/com/dnd/snappy/controller/v1/snap/SnapController.java
  src/main/java/com/dnd/snappy/domain/snap/repository/SnapRepository.java
  src/main/java/com/dnd/snappy/domain/snap/service/SnapService.java
  src/test/java/com/dnd/snappy/controller/v1/snap/SnapControllerTest.java
Labels: Feature

#61 스프링단 로그 추가
  docker-compose.yml
  src/main/java/com/dnd/snappy/common/error/GlobalExceptionHandler.java
  src/main/java/com/dnd/snappy/common/logger/MDCFilter.java
  src/main/java/com/dnd/snappy/common/logger/RequestResponseLogger.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logger/console/console-appender.xml
  src/main/resources/logger/console/parameter-appender.xml
  src/main/resources/logger/file/error-appender.xml
  src/main/resources/logger/file/info-appender.xml
  src/main/resources/logger/file/warn-appender.xml
  src/main/resources/logger/logback-spring-dev.xml
  src/main/resources/logger/logback-spring-local.xml
Labels: Feature

#62 feat: 참여자 ROLE에 따른 모임 비밀번호, 관리자키 조회 api 구현
  src/docs/asciidoc/meeting/find-meeting-password.adoc
  src/docs/asciidoc/meeting/meeting.adoc
  src/main/java/com/dnd/snappy/controller/v1/meeting/MeetingController.java
  src/main/java/com/dnd/snappy/domain/participant/dto/response/MeetingPasswordResponseDto.java
  src/main/java/com/dnd/snappy/domain/participant/repository/ParticipantRepository.java
  src/main/java/com/dnd/snappy/domain/participant/service/ParticipantService.java
  src/test/java/com/dnd/snappy/controller/v1/meeting/MeetingControllerTest.java
Labels: Feature

#64 Feature/#54
  src/docs/asciidoc/mission/meeting-mission-detail.adoc
  src/docs/asciidoc/mission/mission.adoc
  src/main/java/com/dnd/snappy/controller/v1/mission/MissionController.java
  src/main/java/com/dnd/snappy/controller/v1/mission/MissionDetailController.java
  src/main/java/com/dnd/snappy/controller/v1/participant/request/ParticipationRequest.java
  src/main/java/com/dnd/snappy/domain/mission/dto/response/LeaderMeetingMissionDetailResponseDto.java
  src/main/java/com/dnd/snappy/domain/mission/dto/response/MeetingMissionDetailResponseDto.java
  src/main/java/com/dnd/snappy/domain/mission/repository/MissionRepository.java
  src/main/java/com/dnd/snappy/domain/mission/service/MissionDetailService.java
  src/main/java/com/dnd/snappy/domain/mission/service/MissionService.java
  src/test/java/com/dnd/snappy/controller/v1/mission/MissionControllerTest.java
  src/test/java/com/dnd/snappy/controller/v1/mission/MissionDetailControllerTest.java
  src/test/java/com/dnd/snappy/controller/v1/participant/ParticipantControllerTest.java
  src/test/java/com/dnd/snappy/domain/mission/service/MissionDetailServiceTest.java
Labels: Feature, fix

#65 [주최자] 모임 수정하기
  src/docs/asciidoc/meeting/create-meeting.adoc
  src/docs/asciidoc/meeting/meeting.adoc
  src/docs/asciidoc/meeting/modify-meeting.adoc
  src/main/java/com/dnd/snappy/controller/v1/meeting/ModifyMeetingController.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/request/ModifyMeetingRequestDto.java
  src/main/java/com/dnd/snappy/domain/meeting/dto/response/ModifyMeetingResponseDto.java
  src/main/java/com/dnd/snappy/domain/meeting/entity/Meeting.java
  src/main/java/com/dnd/snappy/domain/meeting/exception/MeetingErrorCode.java
  src/main/java/com/dnd/snappy/domain/meeting/service/ModifyMeetingService.java
  src/test/java/com/dnd/snappy/controller/v1/meeting/ModifyMeetingControllerTest.java
  src/test/java/com/dnd/snappy/domain/meeting/service/ModifyMeetingServiceTest.java
  src/test/java/com/dnd/snappy/domain/mission/service/MissionValidationServiceTest.java
Labels: Feature

#67 refactor: 리더의 모임 미션 조회 쿼리 리팩토링 (#41)
  src/main/java/com/dnd/snappy/domain/mission/repository/MissionRepository.java
  src/main/java/com/dnd/snappy/domain/mission/service/MissionDetailService.java
  src/test/java/com/dnd/snappy/domain/mission/service/MissionDetailServiceTest.java
Labels: refactor
